#ifndef _GPIO_INTERFACE_H
#define _GPIO_INTERFACE_H
#include "GPIO_Register.h"
typedef enum {
	GPIO_PIN_0=0,GPIO_PIN_1,GPIO_PIN_2,GPIO_PIN_3,GPIO_PIN_4,GPIO_PIN_5,GPIO_PIN_6,GPIO_PIN_7,GPIO_PIN_8,
	GPIO_PIN_9,GPIO_PIN_10,GPIO_PIN_11,GPIO_PIN_12,GPIO_PIN_13,GPIO_PIN_14,GPIO_PIN_15
}GPIO_PIN_NUM;
typedef enum {
	GPIO_PIN_INPUT=0,GPIO_PIN_OUTPUT,GPIO_PIN_AF,GPIO_PIN_ANALOG
}GPIO_PIN_DIR;
typedef enum {
	GPIO_PIN_OUT_PP=0,GPIO_PIN_OUT_OD
}GPIO_PIN_OUT_TYPE;
typedef enum {
	GPIO_PIN_OUT_LS=0,GPIO_PIN_OUT_MS,GPIO_PIN_OUT_FS,GPIO_PIN_OUT_HS
}GPIO_PIN_OUT_SPEED;
typedef enum {
	GPIO_PIN_NOPULL=0,GPIO_PIN_PULLUP,GPIO_PIN_PULLDOWN
}GPIO_PIN_PULL_UP_DOWN;

typedef enum {
	GPIO_PIN_OUT_LOW=0,GPIO_PIN_OUT_HIGH
}GPIO_PIN_OUT_STATE;
typedef enum {
	GPIO_PIN_ALF0=0,GPIO_PIN_ALF1,GPIO_PIN_ALF2,GPIO_PIN_ALF3,GPIO_PIN_ALF4,GPIO_PIN_ALF5,GPIO_PIN_ALF6,GPIO_PIN_ALF7,GPIO_PIN_ALF8,GPIO_PIN_ALF9,GPIO_PIN_ALF10
	,GPIO_PIN_ALF11,GPIO_PIN_ALF12,GPIO_PIN_ALF13,GPIO_PIN_ALF14,GPIO_PIN_ALF15
}GPIO_PIN_ALTERNATE_FUNCTION;

typedef struct{
	GPIO_RegDef_t*   GPIOx; 
	GPIO_PIN_NUM GPIO_Pin_num;
	GPIO_PIN_DIR Pin_dir;
	GPIO_PIN_OUT_TYPE out_type;
	GPIO_PIN_OUT_SPEED out_speed;
	GPIO_PIN_PULL_UP_DOWN pull_type;
	GPIO_PIN_OUT_STATE pin_state;
	GPIO_PIN_ALTERNATE_FUNCTION ALF_num;
	
}GPIO_PIN_CONFIG;

void GPIO_PIN_Init(GPIO_PIN_CONFIG* pin_config);
void GPIO_PIN_Write(GPIO_RegDef_t* Gpio,GPIO_PIN_NUM pin_num,GPIO_PIN_OUT_STATE u8_state );
void GPIO_PIN_Toggle(GPIO_RegDef_t* Gpio,GPIO_PIN_NUM pin_num);
uint8_t GPIO_PIN_Read(GPIO_RegDef_t* Gpio,GPIO_PIN_NUM pin_num);
#endif /* _GPIO_INTERFACE_H */



